name: EC2 File Creation

on:
  workflow_dispatch:  # Allows manual triggering via GitHub UI

jobs:
  create-file:
    runs-on: ubuntu-latest  # Use a lightweight Ubuntu runner

    steps:
      - name: Create ok.txt file on EC2 if it doesn't exist
        uses: appleboy/ssh-action@v1.2.0  # Specify the version as 1.2.0
        with:
          host: ${{ secrets.HOST_DNS }}  # EC2 instance public DNS (or IP)
          username: ${{ secrets.USERNAME }}  # SSH username (ec2-user or ubuntu)
          key: ${{ secrets.EC2_SSH_KEY }}  # SSH private key for authentication
          port: 22  # SSH port (default is 22)
          script: |
            TARGET_DIR="${{ secrets.TARGET_DIR }}"
            FILE_PATH="${TARGET_DIR}/ok.txt"

            # Check if ok.txt exists, and create it if it doesn't
            if [ ! -f "$FILE_PATH" ]; then
              touch "$FILE_PATH"
              echo "ok.txt file created at $FILE_PATH"
            else
              echo "ok.txt already exists at $FILE_PATH"
            fi
