name: Deploy Nginx with SSL and Reverse Proxy to EC2

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key for EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Copy Python script to EC2
        run: |
          scp -i ec2_key.pem -o StrictHostKeyChecking=no create_nginx_config.py ubuntu@${{ secrets.HOST_DNS }}:/home/ubuntu/

      - name: Install and start Nginx on EC2
        run: |
          ssh -T -i ec2_key.pem ubuntu@${{ secrets.HOST_DNS }} << 'EOF'
            set -e
            # Update package list and install Nginx
            sudo apt-get update
            sudo apt-get install -y nginx

            # Start and enable Nginx service
            sudo systemctl start nginx
            sudo systemctl enable nginx
          EOF

      - name: Execute Python script to configure Nginx and SSL on EC2
        run: |
          ssh -T -i ec2_key.pem ubuntu@${{ secrets.HOST_DNS }} << 'EOF'
            set -e
            # Run the Python script with the domain and port as arguments
            sudo python3 /home/ubuntu/create_nginx_config.py "${{ secrets.DOMAIN_NAME }}" "${{ secrets.PORT }}"

            # Reload Nginx to apply the new configuration
            sudo systemctl reload nginx
            sudo ufw allow 'Nginx Full'
          EOF

      - name: Clean up SSH key
        run: |
          rm -f ec2_key.pem